# Generated by Django 5.0.1 on 2026-07-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_movimentacaoestoque_emitir_nfe_and_more'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe',
            name='movimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='cadastros.movimentacaoestoque', verbose_name='Movimentação Origem'),
        ),
    ]
