# Generated by Django 5.0.1 on 2026-07-18 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_empresa_certificado_digital_empresa_cidade_sede_and_more'),
        ('fiscal', '0002_alter_nfe_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfe',
            name='especie',
            field=models.CharField(blank=True, help_text='Ex.: CAIXA, PALLET, SACO', max_length=60, verbose_name='Espécie'),
        ),
        migrations.AddField(
            model_name='nfe',
            name='modalidade_frete',
            field=models.IntegerField(choices=[(0, '0 - Contratação Frete por conta Emitente'), (1, '1 - Contratação Frete por conta Destinatário'), (2, '2 - Contratação Frete por conta Terceiros'), (3, '3 - Transporte Próprio por conta Remetente'), (4, '4 - Transporte Próprio por conta Destinatário'), (9, '9 - Sem Ocorrência de Transporte')], default=9, verbose_name='Modalidade do Frete'),
        ),
        migrations.AddField(
            model_name='nfe',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Peso Bruto (kg)'),
        ),
        migrations.AddField(
            model_name='nfe',
            name='peso_liquido',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Peso Líquido (kg)'),
        ),
        migrations.AddField(
            model_name='nfe',
            name='transportadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_transporte', to='cadastros.pessoa', verbose_name='Transportadora'),
        ),
        migrations.AddField(
            model_name='nfe',
            name='volumes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Quantidade de Volumes'),
        ),
    ]
