# Generated by Django 5.0.1 on 2026-03-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='Quantidade')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos', to='cadastros.localestoque', verbose_name='Local')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_estoque', to='cadastros.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Saldo de Estoque',
                'verbose_name_plural': 'Saldos de Estoque',
                'db_table': 'estoque_saldo',
                'ordering': ['produto__nome'],
                'unique_together': {('produto', 'local')},
            },
        ),
    ]
