# Generated by Django 5.0.1 on 2026-03-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_saldoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='localestoque',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
