# Generated by Django 5.0.1 on 2026-03-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_localestoque_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='cfop',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='CFOP'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='chave_nfe',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave da NF-e'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.localestoque', verbose_name='Local de Estoque'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='nro_documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='serie',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Série'),
        ),
    ]
