# Generated by Django 5.0.1 on 2026-06-08 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_produto_campos_fiscais'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_realizadas', to='cadastros.pessoa', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='aliquota_mva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Margem de Valor Agregado para ICMS-ST', max_digits=5, verbose_name='MVA (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cfop_venda_estadual',
            field=models.CharField(blank=True, default='', help_text='Ex: 5102, 5405', max_length=4, verbose_name='CFOP Venda Estadual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cfop_venda_interestadual',
            field=models.CharField(blank=True, default='', help_text='Ex: 6102, 6404', max_length=4, verbose_name='CFOP Venda Interestadual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cst_cofins',
            field=models.CharField(blank=True, default='', help_text='Ex: 01=Alíquota básica | 07=Operação isenta | 49=Outras operações | 99=Outras', max_length=2, verbose_name='CST COFINS'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cst_icms',
            field=models.CharField(blank=True, default='', help_text='Régime Normal: 00,10,20,30,40,41,50,60,70,90 | Simples: 101,102,103,201,202,203,300,400,500,900', max_length=3, verbose_name='CST/CSOSN ICMS'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cst_ipi',
            field=models.CharField(blank=True, help_text='Ex: 50=Saída tributada | 99=Outras saídas', max_length=2, null=True, verbose_name='CST IPI'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cst_pis',
            field=models.CharField(blank=True, default='', help_text='Ex: 01=Alíquota básica | 07=Operação isenta | 49=Outras operações | 99=Outras', max_length=2, verbose_name='CST PIS'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='modalidade_bc_icms',
            field=models.IntegerField(default=3, help_text='0=MVA | 1=Pauta | 2=Preço Tabelado | 3=Valor da Operação', verbose_name='Modalidade BC ICMS'),
        ),
    ]
