# Generated by Django 5.0.1 on 2026-06-08 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_movimentacaoestoque_vendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='empresa_config', serialize=False, to='cadastros.pessoa', verbose_name='Pessoa/Empresa')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone_principal', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_esquema', models.CharField(blank=True, help_text='Ex: marilia, bauru', max_length=20, null=True)),
                ('logo_fundo', models.ImageField(blank=True, null=True, upload_to='empresa/logos/')),
                ('juros_mes', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('multa_por_atraso', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('dias_vencimento_padrao_orcamento', models.IntegerField(default=0)),
                ('valor_frete_padrao', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('nao_alterar_valor_frete_padrao', models.BooleanField(default=False)),
                ('numero_serie_certificado_nfe', models.CharField(blank=True, max_length=255, null=True)),
                ('senha_certificado_digital', models.CharField(blank=True, max_length=255, null=True)),
                ('caminho_arquivos_xml', models.CharField(blank=True, max_length=255, null=True)),
                ('uf_web_service_nfe', models.CharField(default='SP', max_length=2)),
                ('ambiente_destino', models.CharField(choices=[('H', 'Homologação'), ('P', 'Produção')], default='H', max_length=1)),
                ('crt_nfe', models.SmallIntegerField(blank=True, choices=[(1, 'Simples Nacional'), (2, 'Simples Nacional - Excesso'), (3, 'Regime Normal')], null=True)),
                ('regime_tributacao_federal', models.IntegerField(choices=[(0, 'Simples Nacional'), (1, 'Lucro Presumido'), (2, 'Lucro Real')], default=0)),
                ('configuracao_estoque_negativo', models.SmallIntegerField(choices=[(1, 'Permitir'), (2, 'Bloquear'), (3, 'Controlar por Divisão')], default=1)),
                ('centro_custo_compra', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_cc_compra', to='cadastros.centrocusto', verbose_name='Centro de Custo Compra')),
                ('centro_custo_venda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_cc_venda', to='cadastros.centrocusto', verbose_name='Centro de Custo Venda')),
                ('cliente_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_cliente_padrao', to='cadastros.pessoa', verbose_name='Cliente Padrão (PDV)')),
                ('consumidor_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_consumidor_final', to='cadastros.pessoa', verbose_name='Pessoa Consumidor Final')),
                ('divisao_padrao_xml', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.divisao')),
                ('local_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.localestoque', verbose_name='Local de Estoque Padrão')),
                ('local_padrao_xml', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_local_xml', to='cadastros.localestoque')),
                ('marca_padrao_xml', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.marca')),
                ('ncm_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.ncm', verbose_name='NCM Padrão')),
                ('plano_contas_receita_compra', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_receita_compra', to='cadastros.planocontas', verbose_name='Plano de Contas (Receita Compra)')),
                ('plano_contas_receita_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_receita_venda', to='cadastros.planocontas', verbose_name='Plano de Contas (Receita Venda)')),
                ('unidade_venda_padrao_xml', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidade')),
                ('vendedor_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_vendedor_padrao', to='cadastros.pessoa', verbose_name='Vendedor Padrão')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
                'db_table': 'empresas',
            },
        ),
    ]
