# Generated by Django 5.0.1 on 2026-06-09 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('pk_chave', models.AutoField(primary_key=True, serialize=False)),
                ('data_abertura', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor de Abertura')),
                ('valor_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor de Fechamento')),
                ('aberto', models.BooleanField(default=True, verbose_name='Caixa Aberto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'db_table': 'caixas',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='TituloFinanceiro',
            fields=[
                ('pk_chave', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('P', 'A Pagar'), ('R', 'A Receber')], max_length=1, verbose_name='Tipo')),
                ('data_operacao', models.DateField(auto_now_add=True, verbose_name='Data de Operação')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número do Documento')),
                ('parcela', models.IntegerField(default=1, verbose_name='Parcela')),
                ('total_parcelas', models.IntegerField(default=1, verbose_name='Total de Parcelas')),
                ('valor_documento', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor do Documento')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Pago')),
                ('valor_saldo', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Saldo')),
                ('situacao', models.CharField(choices=[('ABERTO', 'Aberto'), ('PAGO', 'Pago/Liquidado'), ('CANCELADO', 'Cancelado'), ('ATRASADO', 'Atrasado'), ('PARCIAL', 'Pago Parcial')], default='ABERTO', max_length=20, verbose_name='Situação')),
                ('historico', models.TextField(blank=True, null=True, verbose_name='Histórico/Observação')),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.centrocusto', verbose_name='Centro de Custo')),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.contabancaria', verbose_name='Conta Bancária')),
                ('movimentacao_estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_financeiros', to='cadastros.movimentacaoestoque', verbose_name='Movimentação de Origem')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos_financeiros', to='cadastros.pessoa', verbose_name='Pessoa (Cliente/Fornecedor)')),
                ('plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.planocontas', verbose_name='Plano de Contas')),
                ('tipo_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipopagamento', verbose_name='Tipo de Pagamento')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Título Financeiro',
                'verbose_name_plural': 'Títulos Financeiros',
                'db_table': 'titulos_financeiros',
                'ordering': ['data_vencimento', 'pk_chave'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoCaixa',
            fields=[
                ('pk_chave', models.AutoField(primary_key=True, serialize=False)),
                ('data_movimento', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('tipo_operacao', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo Operação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('historico', models.CharField(max_length=255, verbose_name='Histórico')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='cadastros.caixa', verbose_name='Caixa')),
                ('tipo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipopagamento', verbose_name='Tipo de Pagamento')),
                ('titulo_financeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.titulofinanceiro', verbose_name='Título Relacionado')),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': 'Movimentações de Caixa',
                'db_table': 'movimentacoes_caixa',
                'ordering': ['data_movimento'],
            },
        ),
    ]
