# Generated by Django 5.0.1 on 2026-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_caixa_titulofinanceiro_movimentacaocaixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='emitir_nfe',
            field=models.BooleanField(default=False, verbose_name='Emitir NF-e/NFC-e'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='tipo_documento_fiscal',
            field=models.CharField(blank=True, choices=[('', 'Nenhum'), ('55', 'NF-e'), ('65', 'NFC-e')], default='', max_length=2, verbose_name='Tipo Documento Fiscal'),
        ),
    ]
