# Generated by Django 6.0.6 on 2026-07-17 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_movimentacaoestoque_emitir_nfe_and_more'),
        ('fiscal', '0002_alter_nfe_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='certificado_digital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_vinculada', to='fiscal.certificadodigital', verbose_name='Certificado Digital Ativo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade_sede',
            field=models.ForeignKey(blank=True, help_text='Município da sede da empresa (para identificação do emitente na NF-e)', null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade', verbose_name='Município da Sede'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cnae_fiscal',
            field=models.CharField(blank=True, help_text='Classificação Nacional de Atividades Econômicas (7 dígitos)', max_length=7, verbose_name='CNAE Fiscal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csc',
            field=models.CharField(blank=True, help_text='Código de Segurança do Contribuinte para emissão de NFC-e (fornecido pela SEFAZ)', max_length=36, verbose_name='CSC (Código de Segurança do Contribuinte)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csc_id',
            field=models.CharField(blank=True, help_text='Identificador do CSC para NFC-e', max_length=6, verbose_name='ID do CSC'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='serie_nfce',
            field=models.IntegerField(default=1, verbose_name='Série NFC-e'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='serie_nfe',
            field=models.IntegerField(default=1, verbose_name='Série NF-e'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ultimo_numero_nfce',
            field=models.IntegerField(default=0, verbose_name='Último Nº NFC-e'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ultimo_numero_nfe',
            field=models.IntegerField(default=0, verbose_name='Último Nº NF-e'),
        ),
    ]
