# Generated by Django 5.0.1 on 2026-07-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_empresa_certificado_digital_empresa_cidade_sede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='resp_tec_cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da empresa de software (desenvolvedora do sistema)', max_length=18, verbose_name='CNPJ do Responsável Técnico'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='resp_tec_contato',
            field=models.CharField(blank=True, help_text='Nome da pessoa de contato', max_length=60, verbose_name='Contato do Responsável Técnico'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='resp_tec_csrt',
            field=models.CharField(blank=True, help_text='Código de Segurança do Responsável Técnico (32 caracteres hexadecimais)', max_length=32, verbose_name='CSRT'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='resp_tec_csrt_id',
            field=models.CharField(blank=True, help_text='Identificador do CSRT', max_length=6, verbose_name='ID do CSRT'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='resp_tec_email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='Email do Responsável Técnico'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='resp_tec_fone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Responsável Técnico'),
        ),
    ]
