# Generated by Django 5.0.1 on 2026-07-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_empresa_resp_tec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulofinanceiro',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.centrocusto', verbose_name='Centro de Custo'),
        ),
        migrations.AlterField(
            model_name='titulofinanceiro',
            name='plano_contas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.planocontas', verbose_name='Plano de Contas'),
        ),
    ]
