# Generated by Django 5.0.1 on 2026-07-21 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_alter_titulofinanceiro_centro_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmovimentacaoestoque',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_movimentacao', to='cadastros.localestoque', verbose_name='Local Estoque'),
        ),
    ]
